/**
 * Ulric-X MD - Reaction commands (100+ emoji reactions)
 * Each command sends an anime-style reaction GIF (using Pollinations AI for free generation
 * as fallback) or a simple emoji text reaction.
 */
const axios = require('axios');
const utils = require('../lib/utils');
const config= require('../config');

// Reaction list: command name -> [emoji, descriptive text]
const REACTIONS = [
  ['smile',     ['😊', 'is smiling at']],
  ['happy',     ['😄', 'is happy with']],
  ['laugh',     ['😂', 'is laughing at']],
  ['lol',       ['🤣', 'is rolling on the floor laughing at']],
  ['cry',       ['😭', 'is crying because of']],
  ['sad',       ['😢', 'is sad because of']],
  ['angry',     ['😠', 'is angry at']],
  ['mad',       ['😡', 'is mad at']],
  ['love',      ['❤️', 'loves']],
  ['adore',     ['🥰', 'adores']],
  ['hug',       ['🤗', 'is hugging']],
  ['kiss',      ['😘', 'is kissing']],
  ['wink',      ['😉', 'is winking at']],
  ['shy',       ['😊', 'is being shy with']],
  ['blush',     ['😳', 'is blushing at']],
  ['cool',      ['😎', 'is being cool with']],
  ['chad',      ['🤙', 'is being a chad with']],
  ['dance',     ['🕺', 'is dancing with']],
  ['sing',      ['🎤', 'is singing for']],
  ['wave',      ['👋', 'is waving at']],
  ['thumbsup',  ['👍', 'gives thumbs up to']],
  ['thumbsdown',['👎', 'gives thumbs down to']],
  ['ok',        ['👌', 'says OK to']],
  ['clap',      ['👏', 'is clapping for']],
  ['bow',       ['🙇', 'is bowing to']],
  ['highfive',  ['🖐️', 'high-fives']],
  ['fistbump',  ['👊', 'fist-bumps']],
  ['handshake', ['🤝', 'shakes hands with']],
  ['pat',       ['🫳', 'pats']],
  ['pet',       ['🐶', 'wants to pet']],
  ['cuddle',    ['🤗', 'wants to cuddle with']],
  ['holdhands', ['💑', 'wants to hold hands with']],
  ['confused',  ['🤔', 'is confused by']],
  ['thinking',  ['🤔', 'is thinking about']],
  ['skeptical', ['🤨', 'is skeptical of']],
  ['suspicious',['👀', 'is suspicious of']],
  ['shock',     ['😱', 'is shocked by']],
  ['surprised', ['😮', 'is surprised by']],
  ['amazed',    ['🤩', 'is amazed by']],
  ['wow',       ['-wow', 'is wowed by']],
  ['eww',       ['🤢', 'finds']],
  ['disgust',   ['🤮', 'is disgusted by']],
  ['vomit',     ['🤮', 'threw up because of']],
  ['sleep',     ['😴', 'is sleeping because of']],
  ['tired',     ['🥱', 'is tired']],
  ['bored',     ['😐', 'is bored']],
  ['dead',      ['💀', 'is dead because of']],
  ['rip',       ['⚰️', 'RIP']],
  ['scared',    ['😨', 'is scared of']],
  ['terrified', ['😱', 'is terrified of']],
  ['nervous',   ['😬', 'is nervous about']],
  ['anxious',   ['😰', 'is anxious about']],
  ['worried',   ['😟', 'is worried about']],
  ['relaxed',   ['😌', 'feels relaxed with']],
  ['calm',      ['😇', 'feels calm with']],
  ['blessed',   ['🙏', 'feels blessed by']],
  ['pray',      ['🙏', 'is praying for']],
  ['magic',     ['✨', 'does magic with']],
  ['wizard',    ['🧙', 'casts a spell on']],
  ['witch',     ['🧙‍♀️', 'witches']],
  ['ghost',     ['👻', 'spooks']],
  ['alien',     ['👽', 'is beaming up']],
  ['robot',     ['🤖', 'is processing']],
  ['ninja',     ['🥷', 'is sneaking up on']],
  ['pirate',    ['🏴‍☠️', 'is pirating']],
  ['crown',     ['👑', 'crowns']],
  ['trophy',    ['🏆', 'gives trophy to']],
  ['medal',     ['🥇', 'gives medal to']],
  ['star',      ['⭐', 'gives a star to']],
  ['heart',     ['💖', 'sends heart to']],
  ['fire',      ['🔥', 'finds']],
  ['party',     ['🎉', 'parties with']],
  ['celebrate', ['🎊', 'celebrates']],
  ['cake',      ['🎂', 'gives cake to']],
  ['gift',      ['🎁', 'gives a gift to']],
  ['flower',    ['🌹', 'gives a flower to']],
  ['rocket',    ['🚀', 'rockets with']],
  ['pizza',     ['🍕', 'shares pizza with']],
  ['coffee',    ['☕', 'drinks coffee with']],
  ['beer',      ['🍺', 'drinks beer with']],
  ['cocktail',  ['🍹', 'drinks cocktail with']],
  ['wine',      ['🍷', 'drinks wine with']],
  ['burger',    ['🍔', 'eats burger with']],
  ['donut',     ['🍩', 'shares donut with']],
  ['icecream',  ['🍦', 'eats ice cream with']],
  ['cookie',    ['🍪', 'gives cookie to']],
  ['chocolate', ['🍫', 'shares chocolate with']],
  ['candy',     ['🍬', 'gives candy to']],
  ['boom',      ['💥', 'booms']],
  ['punch',     ['🥊', 'punches']],
  ['kick',      ['🦵', 'kicks']],
  ['slap',      ['👋', 'slaps']],
  ['shoot',     ['🔫', 'shoots']],
  ['sword',     ['⚔️', 'swords with']],
  ['shield',    ['🛡️', 'shields']],
  ['crown2',    ['👑', 'is king with']],
  ['rich',      ['💎', 'feels rich with']],
  ['money',     ['💰', 'makes it rain on']],
  ['cash',      ['💵', 'throws cash at']],
  ['flex',      ['💪', 'flexes on']],
  ['muscle',    ['💪', 'shows muscle to']],
  ['smart',     ['🧠', 'is smarter than']],
  ['genius',    ['💡', 'has a genius idea about']],
  ['idea',      ['💡', 'has an idea about']],
  ['bulb',      ['💡', 'lights up']],
  ['sparkle',   ['✨', 'sparkles at']],
  ['rainbow',   ['🌈', 'shows rainbow to']],
  ['sun',       ['☀️', 'shines sun on']],
  ['moon',      ['🌙', 'shows moon to']],
  ['star2',     ['🌟', 'wishes upon a star for']],
  ['cloud',     ['☁️', 'is cloudy with']],
  ['rain',      ['🌧️', 'rains on']],
  ['snow',      ['❄️', 'snows on']],
  ['lightning', ['⚡', 'zaps']],
  ['ocean',     ['🌊', 'surfs with']],
  ['volcano',   ['🌋', 'erupts at']],
  ['mountain',  ['⛰️', 'climbs with']],
  ['forest',    ['🌲', 'explores forest with']]
];

module.exports = REACTIONS.map(([name, [emoji, action]]) => ({
  name, alias: name === 'lol' ? ['lmao'] : [], category: 'reaction', desc: `Reaction: ${name}`,
  handler: async (ctx) => {
    const target = ctx.mentionedJid?.[0];
    const targetText = target ? `@${target.split('@')[0]}` : 'everyone';
    const sender = ctx.pushname || 'Someone';
    const mentions = target ? [target] : [];
    await ctx.reply(`${emoji} ${sender} ${action} ${targetText}`, { mentions });
  }
}));
